### ISSUE TITLE
Deprecations aren't required

### ISSUE THREAD

**Issue by aaronjensen** [socketry/multipart-post#104]
I ended up updating to the new constants, but I thought I'd let you know that the deprecations aren't working as likely intended as they do not appear to be required when loading `multipart/post`.

**Comment by ioquatix** [comment]
The deprecated constants aren't supposed to be loaded except via the very old files e.g. `lib/parts.rb`. Can you explain what you think the behaviour should be?

**Comment by aaronjensen** [comment]
As 2.3.0 was a new minor version, I would expect it to be backwards compatible with 2.2.3. I was even prepared for the eventuality of changing those constants:

```rb
# multipart-post 3.x will likely move classes we depend on into namespaces
s.add_runtime_dependency "multipart-post", "~> 2.1"
```

I wasn't aware that there were alternatives available when I first added that comment/version pin (I don't think they had been published yet). I was depending on `::Multipartable`, after requiring `net/http/post/multipart`. Once I upgraded to `2.3.0`, my code could not find the `::Multipartable` constant anymore, which broke it. I had to make a change to keep using the new minor version. Had it been a major version update it would have been fine.

It's typical, per semver (and I'm making an assumption here that the intent is to follow it), to not remove constants/methods/do other breaking changes that require code changes in efferents. So, that's what I would have expected--that those constants continue be defined when requiring the same file(s) they were previously defined by.

**Comment by ioquatix** [comment]
Ahh, I understand.

Yes, it was a little tricky and I didn't do it perfectly.

The original implementation had `::Parts` defined in `lib/parts.rb`. We moved the constant into `lib/multipart/post/parts.rb` and also put the deprecated constant in that file. In retrospect, we should have left it in `parts.rb` because defining that top level constant was causing people problems.

Unfortunately, it was just the nature of the situation and a lack of experience on my part that lead to this issue. Unfortunately there is little we can do about it now, but the current release is probably about as good as we can have it.
